## Scalars (0D tensors)

In [23]:
import numpy as np
import matplotlib.pyplot as plt
x = np.array(7)
x

array(7)

In [24]:
print("Dimension of 0D Tensor x is: ", x.ndim)

Dimension of 0D Tensor x is:  0


## Vectors (1D tensors)

In [25]:
x = np.array([7, 4, 16, 28, 14])
x

array([ 7,  4, 16, 28, 14])

In [26]:
print("Dimension of 1D Tensor x is: ", x.ndim)

Dimension of 1D Tensor x is:  1


## Matrices (2D tensors)

In [27]:
x = np.array([[5, 8, 24, 34, 50],
[6, 7, 13, 35, 1],
[17, 80, 44, 6, 21]])
x

array([[ 5,  8, 24, 34, 50],
       [ 6,  7, 13, 35,  1],
       [17, 80, 44,  6, 21]])

In [28]:
print("Dimension of 2D Tensor x is: ", x.ndim)

Dimension of 2D Tensor x is:  2


## 3D tensors and higher-dimensional tensors

In [29]:
from numpy import array

T = array([
  [
  [1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]
  ],
  ])
print(T.shape)
print("3D Tensor T is: ", T)


(3, 3, 3)
3D Tensor T is:  [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [30]:
print("Dimension of 3D Tensor T is: ", T.ndim)

Dimension of 3D Tensor T is:  3
